# Generated by Django 5.1.15 on 2026-03-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DownloadFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("file_url", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField(default=0)),
                ("download_count", models.IntegerField(default=0)),
                (
                    "access_type",
                    models.CharField(
                        choices=[("free", "Free"), ("paid", "Paid"), ("subscription", "Subscription")],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
