# Generated by Django 5.1.15 on 2026-03-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("downloads", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="downloadfile",
            old_name="access_type",
            new_name="pricing_type",
        ),
        migrations.AddField(
            model_name="downloadfile",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
