# Generated by Django 5.1.15 on 2026-06-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("downloads", "0003_simplify_pricing_type"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadfile",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="downloads", to="tags.tag"),
        ),
    ]
