# Generated by Django 5.1.15 on 2026-07-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("downloads", "0004_downloadfile_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadfile",
            name="file_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
