# Generated by Django 5.1.15 on 2026-07-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("downloads", "0005_alter_downloadfile_file_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadfile",
            name="pricing_type",
            field=models.CharField(
                choices=[("free", "Free"), ("paid", "Paid"), ("subscription", "Included in subscription")],
                default="free",
                max_length=20,
            ),
        ),
    ]
