from django.urls import path

from .assistant_views import (
    assistant_config,
    assistant_conversation_message,
    assistant_conversation_release,
    assistant_conversation_takeover,
    assistant_conversation_thread,
    assistant_conversations,
    assistant_knowledge,
    assistant_knowledge_detail,
    assistant_link_detail,
    assistant_links,
    assistant_preview_chat,
    assistant_transcripts,
)
from .cx import views as cx_views
from .demo_content import demo_content, erase_demo_content
from .setup_flow_views import (
    setup_flow_build_page,
    setup_flow_cover,
    setup_flow_draft,
    setup_flow_golive,
    setup_flow_logo_more,
    setup_flow_logos,
    setup_flow_state,
    setup_flow_turn,
)
from .views import (
    TenantConfigView,
    admin_stats,
    help_bot_chat,
    help_bot_human_message,
    help_bot_human_request,
    help_bot_status,
    help_bot_thread,
    logo_ai_status,
    logo_converse,
    logo_converse_finish,
    logo_refine,
    setup_status,
)

urlpatterns = [
    path("config/", TenantConfigView.as_view(), name="tenant-config"),
    path("stats/", admin_stats, name="admin-stats"),
    path("setup-status/", setup_status, name="setup-status"),
    path("setup-flow/", setup_flow_state, name="setup-flow"),
    path("setup-flow/build-page/", setup_flow_build_page, name="setup-flow-build-page"),
    path("setup-flow/draft/", setup_flow_draft, name="setup-flow-draft"),
    path("setup-flow/turn/", setup_flow_turn, name="setup-flow-turn"),
    path("setup-flow/logos/", setup_flow_logos, name="setup-flow-logos"),
    path("setup-flow/logo-more/", setup_flow_logo_more, name="setup-flow-logo-more"),
    path("setup-flow/golive/", setup_flow_golive, name="setup-flow-golive"),
    path("setup-flow/cover/", setup_flow_cover, name="setup-flow-cover"),
    path("demo-content/", demo_content, name="demo-content"),
    path("demo-content/erase/", erase_demo_content, name="demo-content-erase"),
    path("help-bot/chat/", help_bot_chat, name="help-bot-chat"),
    path("help-bot/status/", help_bot_status, name="help-bot-status"),
    path("help-bot/thread/", help_bot_thread, name="help-bot-thread"),
    path("help-bot/human-message/", help_bot_human_message, name="help-bot-human-message"),
    path("help-bot/human-request/", help_bot_human_request, name="help-bot-human-request"),
    path("config/logo-ai/status/", logo_ai_status, name="logo-ai-status"),
    path("config/logo-converse/", logo_converse, name="logo-converse"),
    path("config/logo-converse/finish/", logo_converse_finish, name="logo-converse-finish"),
    path("config/logo-refine/", logo_refine, name="logo-refine"),
    path("cx/compose/", cx_views.cx_compose, name="cx-compose"),
    path("cx/refine/", cx_views.cx_refine, name="cx-refine"),
    path("cx/components/", cx_views.cx_components, name="cx-components"),
    path("assistant/config/", assistant_config, name="assistant-config"),
    path("assistant/knowledge/", assistant_knowledge, name="assistant-knowledge"),
    path("assistant/knowledge/<int:pk>/", assistant_knowledge_detail, name="assistant-knowledge-detail"),
    path("assistant/links/", assistant_links, name="assistant-links"),
    path("assistant/links/<int:pk>/", assistant_link_detail, name="assistant-link-detail"),
    path("assistant/transcripts/", assistant_transcripts, name="assistant-transcripts"),
    path("assistant/preview-chat/", assistant_preview_chat, name="assistant-preview-chat"),
    path("assistant/conversations/", assistant_conversations, name="assistant-conversations"),
    path(
        "assistant/conversations/<int:pk>/thread/",
        assistant_conversation_thread,
        name="assistant-conversation-thread",
    ),
    path(
        "assistant/conversations/<int:pk>/takeover/",
        assistant_conversation_takeover,
        name="assistant-conversation-takeover",
    ),
    path(
        "assistant/conversations/<int:pk>/message/",
        assistant_conversation_message,
        name="assistant-conversation-message",
    ),
    path(
        "assistant/conversations/<int:pk>/release/",
        assistant_conversation_release,
        name="assistant-conversation-release",
    ),
]
