# Generated by Django 5.1.15 on 2026-03-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="liveclass",
            old_name="rtk_meeting_id",
            new_name="zoom_meeting_id",
        ),
        migrations.AddField(
            model_name="liveclass",
            name="zoom_join_url",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="liveclass",
            name="zoom_passcode",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
