# Generated by Django 5.1.15 on 2026-03-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0002_rename_rtk_meeting_id_liveclass_zoom_meeting_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liveclass",
            name="mode",
        ),
        migrations.AddField(
            model_name="liveclass",
            name="auto_recording",
            field=models.CharField(choices=[("none", "None"), ("cloud", "Cloud")], default="none", max_length=10),
        ),
        migrations.AddField(
            model_name="liveclass",
            name="chat_scope",
            field=models.CharField(
                choices=[("host_only", "Host Only"), ("everyone", "Everyone")], default="everyone", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="liveclass",
            name="duration",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="liveclass",
            name="mute_on_entry",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="liveclass",
            name="participant_video",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="liveclass",
            name="screen_sharing",
            field=models.CharField(
                choices=[("host", "Host Only"), ("all", "All Participants")], default="host", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="liveclass",
            name="waiting_room",
            field=models.BooleanField(default=True),
        ),
    ]
