# Generated by Django 5.1.15 on 2026-03-19 20:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0003_remove_liveclass_mode_liveclass_auto_recording_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liveclass",
            name="auto_recording",
        ),
        migrations.RemoveField(
            model_name="liveclass",
            name="chat_scope",
        ),
        migrations.RemoveField(
            model_name="liveclass",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="liveclass",
            name="mute_on_entry",
        ),
        migrations.RemoveField(
            model_name="liveclass",
            name="participant_video",
        ),
        migrations.RemoveField(
            model_name="liveclass",
            name="screen_sharing",
        ),
        migrations.RemoveField(
            model_name="liveclass",
            name="waiting_room",
        ),
        migrations.RemoveField(
            model_name="liveclass",
            name="zoom_join_url",
        ),
        migrations.RemoveField(
            model_name="liveclass",
            name="zoom_meeting_id",
        ),
        migrations.RemoveField(
            model_name="liveclass",
            name="zoom_passcode",
        ),
    ]
