# Generated by Django 5.1.15 on 2026-03-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0004_remove_liveclass_auto_recording_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveclass",
            name="recording_url",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
    ]
