# Generated by Django 5.1.15 on 2026-03-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0005_liveclass_recording_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveclass",
            name="auto_recording",
            field=models.BooleanField(default=False),
        ),
    ]
