# Generated by Django 5.1.15 on 2026-03-20 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0009_backfill_recording_fk"),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveclass",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="live_classes",
                to="media.photo",
            ),
        ),
        migrations.AddField(
            model_name="livestream",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="live_streams",
                to="media.photo",
            ),
        ),
    ]
