# Generated by Django 5.1.15 on 2026-03-22 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live", "0011_backfill_thumbnail_photos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnsiteEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("ongoing", "Ongoing"),
                            ("ended", "Ended"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, default="", max_length=500)),
                ("address", models.TextField(blank=True, default="")),
                ("max_capacity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[("free", "Free"), ("paid", "Paid"), ("subscription", "Subscription")],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onsite_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ZoomClass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("scheduled", "Scheduled"), ("live", "Live"), ("ended", "Ended")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("zoom_link", models.URLField(blank=True, default="", max_length=500)),
                ("zoom_meeting_id", models.CharField(blank=True, default="", max_length=100)),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[("free", "Free"), ("paid", "Paid"), ("subscription", "Subscription")],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zoom_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
