# Generated by Django 5.1.15 on 2026-03-22 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0013_add_duration_minutes'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsiteevent',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onsite_events', to='media.photo'),
        ),
        migrations.AddField(
            model_name='onsiteevent',
            name='thumbnail_url',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='zoomclass',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zoom_classes', to='media.photo'),
        ),
        migrations.AddField(
            model_name='zoomclass',
            name='thumbnail_url',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
