# Generated by Django 5.1.15 on 2026-06-22 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_alter_announcement_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="also_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="announcementrecipient",
            name="email_status",
            field=models.CharField(
                choices=[("none", "None"), ("sent", "Sent"), ("failed", "Failed")], default="none", max_length=10
            ),
        ),
        migrations.CreateModel(
            name="EmailOptOut",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.CharField(db_index=True, max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
