# Generated by Django 5.1.15 on 2026-07-11 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('media', '0002_photo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.photo'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_placements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
