# Generated by Django 5.1.15 on 2026-06-30 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('counterparty_email',), name='uniq_open_conversation_per_counterparty'),
        ),
    ]
