# Generated by Django 5.1.15 on 2026-05-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_tenant_billing_currency_tenant_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformplan",
            name="prices",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
