# Generated by Django 5.1.15 on 2026-05-12.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_backfill_free_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="slug",
            field=models.SlugField(max_length=63),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="subdomain",
            field=models.CharField(max_length=63),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.UniqueConstraint(fields=("slug", "region"), name="core_tenant_slug_region_unique"),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.UniqueConstraint(
                fields=("subdomain", "region"), name="core_tenant_subdomain_region_unique"
            ),
        ),
    ]
