# Generated by Django 5.1.15 on 2026-05-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_tenant_is_demo"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tenant",
            name="core_tenant_slug_region_unique",
        ),
        migrations.RemoveConstraint(
            model_name="tenant",
            name="core_tenant_subdomain_region_unique",
        ),
        migrations.AlterField(
            model_name="tenant",
            name="slug",
            field=models.SlugField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="subdomain",
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
