# Generated by Django 5.1.15 on 2026-06-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tenant_template_seed_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformplan',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
