# Generated by Django 5.1.15 on 2026-06-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_platformplan_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="stripe_charges_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="stripe_payouts_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
