# Generated by Django 5.1.15 on 2026-07-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_devoutboundemail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformsubscription",
            name="provider",
            field=models.CharField(
                choices=[("stripe", "Stripe"), ("bypass", "Bypass"), ("manual", "Manual")],
                default="stripe",
                max_length=20,
            ),
        ),
    ]
