# Generated by Django 5.1.15 on 2026-07-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_platformblogpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiTranscript",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("feature", models.CharField(max_length=20)),
                ("audience", models.CharField(max_length=10)),
                ("tenant_schema", models.CharField(max_length=63)),
                ("session_id", models.CharField(blank=True, default="", max_length=36)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("cost_usd", models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ("provider", models.CharField(max_length=12)),
                ("model", models.CharField(max_length=40)),
                ("prompt_version", models.PositiveSmallIntegerField(default=1)),
                ("kb_hash", models.CharField(blank=True, default="", max_length=12)),
                ("rating", models.CharField(blank=True, default="", max_length=4)),
                ("is_preview", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["feature", "created_at"], name="core_aitran_feature_fedd0b_idx"),
                    models.Index(fields=["tenant_schema", "created_at"], name="core_aitran_tenant__00e840_idx"),
                    models.Index(fields=["session_id"], name="core_aitran_session_23e7ec_idx"),
                ],
            },
        ),
    ]
