# Generated by Django 5.1.15 on 2026-07-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_aitranscript"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformplan",
            name="max_student_bot_questions",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="StudentBotUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_schema", models.CharField(max_length=63)),
                ("month", models.CharField(max_length=7)),
                ("questions", models.PositiveIntegerField(default=0)),
                ("usd_spent", models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_schema", "month"), name="uniq_student_bot_usage_tenant_month"
                    )
                ],
            },
        ),
    ]
