# Generated by Django 5.1.15 on 2026-07-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_platformplan_max_student_bot_questions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformKbEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "audience",
                    models.CharField(
                        choices=[("coach", "Coach"), ("visitor", "Visitor"), ("student", "Student"), ("all", "All")],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("content", models.TextField(max_length=2000)),
                ("enabled", models.BooleanField(default=True)),
                ("position", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
    ]
