# Generated by Django 5.1.15 on 2026-07-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_platformkbentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='logoaiusage',
            name='refinements_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
