# Generated by Django 5.1.15 on 2026-07-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_aiconversation_aimessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiIpBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip", models.GenericIPAddressField(unique=True)),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                (
                    "source",
                    models.CharField(choices=[("manual", "manual"), ("auto", "auto")], default="manual", max_length=8),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
