# Generated by Django 5.1.15 on 2026-07-11 07:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_logoaiusage_refinements_used"),
        ("core", "0023_aiipblock"),
    ]

    operations = []
