# Generated by Django 5.1.15 on 2026-07-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_merge_20260711_0707"),
    ]

    operations = [
        migrations.AddField(
            model_name="logoaiusage",
            name="turns_used",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
