# Generated by Django 5.1.15 on 2026-07-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_curatedlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedlogo',
            name='mark_paths',
            field=models.JSONField(blank=True, help_text='Traced vector mark ({d, fill} dicts), or null when the PNG did not vectorize cleanly.', null=True),
        ),
    ]
