# Generated by Django 5.1.15 on 2026-07-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_tenant_wizard_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingAiUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_schema", models.CharField(max_length=63)),
                ("month", models.CharField(max_length=7)),
                ("composes_used", models.PositiveIntegerField(default=0)),
                ("usd_spent", models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_schema", "month"), name="uniq_onboarding_ai_usage_tenant_month"
                    )
                ],
            },
        ),
    ]
