# Generated by Django 5.1.15 on 2026-07-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_tenant_recovery_email_sent_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuratedPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120)),
                ("prompt", models.TextField(blank=True, default="")),
                ("tags", models.CharField(blank=True, default="", max_length=500)),
                ("alt_text", models.CharField(blank=True, default="", max_length=300)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("hero", "hero"),
                            ("stock", "stock"),
                            ("spot", "spot"),
                            ("texture", "texture"),
                            ("divider", "divider"),
                            ("icon", "icon"),
                        ],
                        default="stock",
                        max_length=10,
                    ),
                ),
                ("image_key", models.CharField(max_length=300)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("position", models.IntegerField(default=0, help_text="Sort order; 0 = append at the end on create.")),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
    ]
