# Generated by Django 5.1.15 on 2026-07-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_curatedphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='is_demo',
        ),
    ]
