# Generated by Django 5.1.15 on 2026-07-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_free_blog_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='abandon_warned_at',
            field=models.DateTimeField(blank=True, help_text="When the final 'your signup will be deleted' warning was sent. NULL = not yet warned. Stage 2 of cleanup deletes the tenant WIZARD_ABANDON_DELETE_GRACE_DAYS after this timestamp.", null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='provisioning_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('provisioned', 'Schema ready (site not yet composed)'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
