# Generated by Django 5.1.15 on 2026-10-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_curatedphoto_decorative_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="billing_currency",
            field=models.CharField(
                blank=True,
                choices=[("USD", "US Dollar"), ("EUR", "Euro")],
                default="",
                help_text="Set at first Stripe checkout, immutable thereafter.",
                max_length=3,
            ),
        ),
    ]
