# Generated by Django 5.1.15 on 2026-10-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_tenant_billing_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='iyzico_submerchant_id',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='region',
            field=models.CharField(choices=[('global', 'Global')], db_index=True, default='global', help_text='Immutable. Set at signup from the request host.', max_length=8),
        ),
    ]
