# Generated by Django 5.1.15 on 2026-10-08 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_remove_tenant_iyzico_submerchant_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CxComponent",
            fields=[
                ("id", models.CharField(max_length=12, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=60)),
                ("summary", models.CharField(blank=True, default="", max_length=200)),
                ("author_tenant_schema", models.CharField(db_index=True, max_length=63)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("shared", "Shared"),
                            ("featured", "Featured"),
                            ("hidden", "Hidden"),
                        ],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("latest_version", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CxVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("n", models.PositiveIntegerField()),
                ("spec", models.JSONField()),
                ("content", models.JSONField(blank=True, default=dict)),
                ("prompt", models.TextField(blank=True, default="")),
                ("missing_capabilities", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="core.cxcomponent"
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("component", "n"), name="uniq_cx_version_n")],
            },
        ),
    ]
