api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    exposedByDefault: false
    network: contentor_default
  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: INFO
