# Generated by Django 5.1.15 on 2026-10-04 18:21

from django.db import connection, migrations, models

import apps.core.currency


def rewrite_try_to_tenant_currency(apps, schema_editor):
    """Pre-launch rows were stamped TRY by the old default; students must see the
    tenant's own currency. Real Stripe payments keep their true charge currency —
    only bypass (offline) payments are rewritten."""
    # django-tenants runs migrations with a FakeTenant carrying only the schema
    # name, so read the real currency straight from the public tenant table.
    schema = connection.schema_name
    if schema == "public":
        return
    with connection.cursor() as cur:
        cur.execute("SELECT billing_currency FROM public.core_tenant WHERE schema_name = %s", [schema])
        row = cur.fetchone()
    currency = ((row[0] if row else "") or "").strip() or "USD"
    apps.get_model("billing", "SubscriptionPlan").objects.filter(currency="TRY").update(currency=currency)
    apps.get_model("billing", "Bundle").objects.filter(currency="TRY").update(currency=currency)
    apps.get_model("billing", "Subscription").objects.filter(billing_currency="TRY").update(billing_currency=currency)
    apps.get_model("billing", "Payment").objects.filter(provider="bypass", currency="TRY").update(currency=currency)


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0006_subscriptionplan_billing_interval_months_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bundle",
            name="currency",
            field=models.CharField(default=apps.core.currency.tenant_charge_currency, max_length=3),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="billing_currency",
            field=models.CharField(default=apps.core.currency.tenant_charge_currency, max_length=3),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="currency",
            field=models.CharField(default=apps.core.currency.tenant_charge_currency, max_length=3),
        ),
        migrations.RunPython(rewrite_try_to_tenant_currency, migrations.RunPython.noop),
    ]
