# Generated by Django 5.1.15 on 2026-08-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform_email", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformemailcampaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("partial", "Partial"),
                    ("failed", "Failed"),
                ],
                default="sending",
                max_length=20,
            ),
        ),
    ]
