# Generated by Django 5.1.15 on 2026-03-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail_url',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
