# Generated by Django 5.1.15 on 2026-03-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_backfill_thumbnail_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="file_size",
            field=models.BigIntegerField(default=0),
        ),
    ]
