# Generated by Django 5.1.15 on 2026-03-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_video_file_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
