# Generated by Django 5.1.15 on 2026-06-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_coursecategory_course_categories'),
        ('filters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='categories',
        ),
        migrations.AddField(
            model_name='course',
            name='filter_options',
            field=models.ManyToManyField(blank=True, related_name='courses', to='filters.filteroption'),
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
    ]
