# Generated by Django 5.1.15 on 2026-03-20 21:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("s3_key", models.CharField(max_length=500)),
                ("alt_text", models.CharField(blank=True, default="", max_length=300)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("content_type", models.CharField(blank=True, default="", max_length=100)),
                ("file_size", models.BigIntegerField(default=0)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
