# Generated by Django 5.1.15 on 2026-06-20 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('pwa', 'PWA'), ('browser', 'Browser')], max_length=10)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('desktop', 'Desktop'), ('other', 'Other')], max_length=10)),
                ('day', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mode', 'platform', 'day')},
            },
        ),
    ]
