# Generated by Django 5.1.15 on 2026-07-19 21:27

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="LogArchiveDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("kind", models.CharField(choices=[("logs", "logs"), ("activity", "activity")], max_length=10)),
                ("object_key", models.CharField(blank=True, default="", max_length=256)),
                ("line_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("date", "kind"), name="logbook_archiveday_unique")],
            },
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ts", models.DateTimeField()),
                ("container", models.CharField(max_length=64)),
                ("stream", models.CharField(default="stdout", max_length=8)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "DEBUG"),
                            ("INFO", "INFO"),
                            ("WARNING", "WARNING"),
                            ("ERROR", "ERROR"),
                            ("CRITICAL", "CRITICAL"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("logger_name", models.CharField(blank=True, default="", max_length=128)),
                ("tenant", models.CharField(blank=True, default="", max_length=63)),
                ("user_label", models.CharField(blank=True, default="", max_length=254)),
                ("message", models.TextField()),
                ("line_hash", models.CharField(max_length=32)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["level", "ts"], name="logbook_le_level_ts"),
                    models.Index(fields=["container", "ts"], name="logbook_le_container_ts"),
                    models.Index(fields=["tenant", "ts"], name="logbook_le_tenant_ts"),
                    models.Index(fields=["user_label", "ts"], name="logbook_le_user_ts"),
                    models.Index(fields=["ts"], name="logbook_le_ts"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["message"], name="logbook_msg_trgm", opclasses=["gin_trgm_ops"]
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("container", "ts", "line_hash"), name="logbook_logentry_dedupe")
                ],
            },
        ),
        migrations.CreateModel(
            name="RequestEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ts", models.DateTimeField()),
                (
                    "kind",
                    models.CharField(choices=[("api", "api"), ("pageview", "pageview")], default="api", max_length=10),
                ),
                ("tenant", models.CharField(blank=True, default="", max_length=63)),
                ("user_label", models.CharField(blank=True, default="", max_length=254)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, default="", max_length=36)),
                ("method", models.CharField(blank=True, default="", max_length=8)),
                ("path", models.CharField(blank=True, default="", max_length=512)),
                ("status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("referrer", models.CharField(blank=True, default="", max_length=512)),
                ("user_agent", models.CharField(blank=True, default="", max_length=256)),
                ("line_hash", models.CharField(max_length=32)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["kind", "ts"], name="logbook_re_kind_ts"),
                    models.Index(fields=["tenant", "ts"], name="logbook_re_tenant_ts"),
                    models.Index(fields=["user_label", "ts"], name="logbook_re_user_ts"),
                    models.Index(fields=["session_id", "ts"], name="logbook_re_session_ts"),
                    models.Index(fields=["ip", "ts"], name="logbook_re_ip_ts"),
                    models.Index(fields=["ts"], name="logbook_re_ts"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("kind", "ts", "line_hash"), name="logbook_requestevent_dedupe")
                ],
            },
        ),
    ]
