import {
  Activity,
  Apple,
  Armchair,
  Baby,
  BadgeCheck,
  BadgeDollarSign,
  BedDouble,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  Calendar,
  CalendarDays,
  Camera,
  ChefHat,
  CircleHelp,
  Clock,
  Coffee,
  Coins,
  Compass,
  Crown,
  Dumbbell,
  Feather,
  Flame,
  Flower2,
  Footprints,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Guitar,
  Hand,
  HandHeart,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Hourglass,
  Infinity,
  Instagram,
  Languages,
  Laptop,
  Layers,
  LayoutGrid,
  Leaf,
  Lightbulb,
  ListChecks,
  LockOpen,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  Mic,
  Moon,
  Mountain,
  Music,
  Newspaper,
  Paintbrush,
  Palette,
  PenLine,
  PersonStanding,
  Phone,
  PiggyBank,
  Repeat,
  Rocket,
  Salad,
  School,
  Scissors,
  Shield,
  Shirt,
  Smile,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Store,
  Sun,
  SunMedium,
  Sunrise,
  Sunset,
  Target,
  Ticket,
  Timer,
  Trees,
  Trophy,
  Type,
  UserRound,
  Users,
  UsersRound,
  Video,
  Wallet,
  Waves,
  Wind,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Icon ids the guide may send on an answer (mirrors ICONS in
 *  backend/apps/tenant_config/interview_brief.py; a vitest checks it). */
export const OPTION_ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  apple: Apple,
  armchair: Armchair,
  baby: Baby,
  "badge-check": BadgeCheck,
  "badge-dollar-sign": BadgeDollarSign,
  "bed-double": BedDouble,
  bike: Bike,
  "book-open": BookOpen,
  brain: Brain,
  briefcase: Briefcase,
  "building-2": Building2,
  calendar: Calendar,
  "calendar-days": CalendarDays,
  camera: Camera,
  "chef-hat": ChefHat,
  "circle-help": CircleHelp,
  clock: Clock,
  coffee: Coffee,
  coins: Coins,
  compass: Compass,
  crown: Crown,
  dumbbell: Dumbbell,
  feather: Feather,
  flame: Flame,
  "flower-2": Flower2,
  footprints: Footprints,
  gem: Gem,
  gift: Gift,
  glasses: Glasses,
  globe: Globe,
  "graduation-cap": GraduationCap,
  guitar: Guitar,
  hand: Hand,
  "hand-heart": HandHeart,
  headphones: Headphones,
  heart: Heart,
  "heart-pulse": HeartPulse,
  home: Home,
  hourglass: Hourglass,
  infinity: Infinity,
  instagram: Instagram,
  languages: Languages,
  laptop: Laptop,
  layers: Layers,
  "layout-grid": LayoutGrid,
  leaf: Leaf,
  lightbulb: Lightbulb,
  "list-checks": ListChecks,
  "lock-open": LockOpen,
  mail: Mail,
  "map-pin": MapPin,
  megaphone: Megaphone,
  "message-circle": MessageCircle,
  mic: Mic,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  newspaper: Newspaper,
  paintbrush: Paintbrush,
  palette: Palette,
  "pen-line": PenLine,
  "person-standing": PersonStanding,
  phone: Phone,
  "piggy-bank": PiggyBank,
  repeat: Repeat,
  rocket: Rocket,
  salad: Salad,
  school: School,
  scissors: Scissors,
  shield: Shield,
  shirt: Shirt,
  smile: Smile,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  stethoscope: Stethoscope,
  store: Store,
  sun: Sun,
  "sun-medium": SunMedium,
  sunrise: Sunrise,
  sunset: Sunset,
  target: Target,
  ticket: Ticket,
  timer: Timer,
  trees: Trees,
  trophy: Trophy,
  type: Type,
  "user-round": UserRound,
  users: Users,
  "users-round": UsersRound,
  video: Video,
  wallet: Wallet,
  waves: Waves,
  wind: Wind,
  zap: Zap,
};
