# Generated by Django 5.1.15 on 2026-03-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_config', '0002_alter_tenantconfig_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='landing_sections',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='navbar_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tenantconfig',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
