# Generated by Django 5.1.15 on 2026-03-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_config', '0003_tenantconfig_landing_sections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantconfig',
            name='logo_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
