# Generated by Django 5.1.15 on 2026-03-17 21:20

from django.db import migrations, models


def migrate_theme_from_primary_color(apps, schema_editor):
    TenantConfig = apps.get_model("tenant_config", "TenantConfig")

    for config in TenantConfig.objects.all():
        config.theme = "slate" if config.primary_color == "#171717" else "ocean"
        config.save(update_fields=["theme"])


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_config", "0004_alter_tenantconfig_logo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantconfig",
            name="theme",
            field=models.CharField(
                choices=[
                    ("ocean", "Ocean"),
                    ("ember", "Ember"),
                    ("forest", "Forest"),
                    ("sunset", "Sunset"),
                    ("violet", "Violet"),
                    ("slate", "Slate"),
                ],
                default="ocean",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="tenantconfig",
            name="dark_mode_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(migrate_theme_from_primary_color, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="tenantconfig",
            name="primary_color",
        ),
        migrations.RemoveField(
            model_name="tenantconfig",
            name="secondary_color",
        ),
    ]
