# Generated by Django 5.1.15 on 2026-03-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_config", "0005_tenantconfig_theme_and_dark_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantconfig",
            name="logo_url",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
    ]
