# Generated by Django 5.1.15 on 2026-03-20 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
        ("tenant_config", "0006_alter_tenant_config_logo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantconfig",
            name="logo",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.photo"
            ),
        ),
    ]
