# Generated by Django 5.1.15 on 2026-03-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_config", "0009_tenantconfig_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantconfig",
            name="emailcraft_api_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
