# Generated by Django 5.1.15 on 2026-06-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_config", "0013_backfill_pages_from_landing_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantconfig",
            name="page_templates",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
