# Generated by Django 5.1.15 on 2026-07-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_config', '0014_tenantconfig_page_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='setup_guide_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
