# Generated by Django 5.1.15 on 2026-07-07 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0002_photo_tags"),
        ("tenant_config", "0016_tenantconfig_setup_progress_seededobject"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantconfig",
            name="icon",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="media.photo"
            ),
        ),
        migrations.AddField(
            model_name="tenantconfig",
            name="icon_url",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="tenantconfig",
            name="logo_recipe",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
