# Generated by Django 5.1.15 on 2026-07-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_config", "0018_assistantconfig_assistantknowledgeentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistantconfig",
            name="human_handoff_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
