# Generated by Django 5.1.15 on 2026-07-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_config", "0019_assistantconfig_human_handoff_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=60)),
                ("url", models.CharField(max_length=500)),
                ("note", models.CharField(blank=True, default="", max_length=160)),
                ("enabled", models.BooleanField(default=True)),
                ("position", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
    ]
