# Generated by Django 5.1.15 on 2026-08-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_config", "0021_copilotaudit"),
    ]

    operations = [
        migrations.AddField(
            model_name="copilotaudit",
            name="inverse",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="copilotaudit",
            name="undone_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
