# Generated by Django 5.1.15 on 2026-10-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_config", "0024_alter_tenantconfig_default_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantconfig",
            name="style",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
