# Generated by Django 5.1.15 on 2026-10-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_config", "0025_tenantconfig_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantconfig",
            name="setup_flow",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
