# Generated by Django 5.1.15 on 2026-10-10 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0002_photo_tags"),
        ("tenant_config", "0027_tenantconfig_palette"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogoCandidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("batch", models.CharField(db_index=True, max_length=16)),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[("ready", "ready"), ("rejected", "rejected")], default="ready", max_length=10
                    ),
                ),
                ("reject_reason", models.CharField(blank=True, default="", max_length=40)),
                ("source", models.CharField(choices=[("hub", "hub"), ("api", "api")], default="hub", max_length=8)),
                ("concept", models.TextField()),
                ("archetype", models.CharField(max_length=16)),
                ("prompt", models.TextField()),
                ("vector", models.JSONField(blank=True, null=True)),
                ("rank", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("judge_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="media.photo",
                    ),
                ),
                (
                    "png",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="media.photo",
                    ),
                ),
            ],
            options={
                "ordering": ["batch", "rank", "position"],
            },
        ),
    ]
