# Generated by Django 5.1.15 on 2026-06-23 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0012_tenant_publish_gate"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomDomain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("registrar", models.CharField(default="route53", max_length=20)),
                ("registrar_status", models.CharField(blank=True, default="", max_length=40)),
                ("cloudflare_zone_id", models.CharField(blank=True, default="", max_length=64)),
                ("resend_domain_id", models.CharField(blank=True, default="", max_length=64)),
                ("forward_to_email", models.EmailField(blank=True, default="", max_length=254)),
                ("contact", models.JSONField(blank=True, default=dict)),
                ("cost_minor", models.IntegerField()),
                ("price_minor", models.IntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("fx_rate", models.FloatField(default=1.0)),
                (
                    "provisioning_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("registering", "Registering"),
                            ("dns_zone", "Creating DNS zone"),
                            ("dns_records", "Creating DNS records"),
                            ("email_auth", "Configuring email"),
                            ("ssl", "Issuing SSL"),
                            ("live", "Live"),
                            ("failed", "Failed"),
                            ("lapsed", "Lapsed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("failed_step", models.CharField(blank=True, default="", max_length=40)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(default=True)),
                ("is_primary", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="custom_domains", to="core.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DomainSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(default="stripe", max_length=20)),
                ("provider_subscription_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("provider_customer_id", models.CharField(blank=True, default="", max_length=255)),
                ("status", models.CharField(default="incomplete", max_length=20)),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "custom_domain",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="domains.customdomain",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_subscriptions",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
    ]
