# Generated by Django 5.1.15 on 2026-06-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customdomain",
            name="dns_records_done",
            field=models.BooleanField(default=False),
        ),
    ]
